"""add_outline_status_and_content_fields

Revision ID: 20c8e8cc73fc
Revises: c6d455a002ed
Create Date: 2026-04-02 14:54:57.023674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c8e8cc73fc'
down_revision: Union[str, Sequence[str], None] = 'c6d455a002ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
