"""add_duplicate_of_formal_id

Revision ID: 27a17c220348
Revises: 4ce82408b5ad
Create Date: 2026-04-03 00:08:23.269064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a17c220348'
down_revision: Union[str, Sequence[str], None] = '4ce82408b5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_formal_id', sa.Integer(), nullable=True, comment='疑似重复的正式库ID'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_staging', schema=None) as batch_op:
        batch_op.drop_column('duplicate_of_formal_id')

    # ### end Alembic commands ###
