"""add_difficulty_field

Revision ID: 3274914add2c
Revises: 6288407ee7a2
Create Date: 2026-04-06 22:59:29.517255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3274914add2c'
down_revision: Union[str, Sequence[str], None] = '6288407ee7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度系数 (1-10)'))

    with op.batch_alter_table('question_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度系数 (1-10)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_staging', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
