"""Add status and content to Outline

Revision ID: 4ce82408b5ad
Revises: 20c8e8cc73fc
Create Date: 2026-04-02 15:38:09.282328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce82408b5ad'
down_revision: Union[str, Sequence[str], None] = '20c8e8cc73fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True, comment='大纲原文文本'))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True, comment='大纲状态 (Draft, Active, Archived)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
