"""Add soft delete and cascading

Revision ID: c6d455a002ed
Revises: 
Create Date: 2026-04-02 14:53:28.543309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d455a002ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除标记'))
        batch_op.create_index(batch_op.f('ix_outline_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outline_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
